In [1]:
import numpy as np

In [5]:

data = np.load(r"C:\Users\mathi\Desktop\TU Delft\TU Delft year 5\Master Thesis\Thesis-project-DGM\datasets\training\sample_6.npz")
print(data['facies'].shape)
print(data['facies'])

(64, 256, 256)
[[[2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  ...
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]]

 [[2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  ...
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]]

 [[2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  ...
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]]

 ...

 [[7 7 7 ... 2 2 2]
  [7 7 7 ... 2 2 2]
  [7 7 7 ... 2 2 2]
  ...
  [2 2 2 ... 1 1 3]
  [2 2 2 ... 2 1 1]
  [1 2 2 ... 3 1 1]]

 [[8 8 8 ... 7 7 7]
  [8 8 8 ... 7 7 7]
  [8 8 8 ... 7 7 7]
  ...
  [2 2 2 ... 2 2 2]
  [1 2 2 ... 2 2 2]
  [2 1 1 ... 2 2 2]]

 [[7 7 7 ... 7 7 7]
  [7 7 7 ... 7 7 7]
  [7 7 7 ... 7 7 7]
  ...
  [2 2 2 ... 2 2 2]
  [2 1 1 ... 2 2 2]
  [2 2 2 ... 2 2 2]]]


In [8]:
print(data['facies'][-64:,:,:].shape)
print(data['facies'][-1:,:,:])

(64, 256, 256)
[[[7 7 7 ... 7 7 7]
  [7 7 7 ... 7 7 7]
  [7 7 7 ... 7 7 7]
  ...
  [2 2 2 ... 2 2 2]
  [2 1 1 ... 2 2 2]
  [2 2 2 ... 2 2 2]]]
