In [ ]:
import numpy as np

In [20]:

data = np.load(r"C:\Users\mathi\Desktop\TU Delft\TU Delft year 5\Master Thesis\Thesis-project-DGM\datasets\training\sample_6.npz")["facies"]
print(data.shape)
print(data)

(64, 256, 256)
[[[2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  ...
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]]

 [[2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  ...
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]]

 [[2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  ...
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]]

 ...

 [[7 7 7 ... 2 2 2]
  [7 7 7 ... 2 2 2]
  [7 7 7 ... 2 2 2]
  ...
  [2 2 2 ... 1 1 3]
  [2 2 2 ... 2 1 1]
  [1 2 2 ... 3 1 1]]

 [[8 8 8 ... 7 7 7]
  [8 8 8 ... 7 7 7]
  [8 8 8 ... 7 7 7]
  ...
  [2 2 2 ... 2 2 2]
  [1 2 2 ... 2 2 2]
  [2 1 1 ... 2 2 2]]

 [[7 7 7 ... 7 7 7]
  [7 7 7 ... 7 7 7]
  [7 7 7 ... 7 7 7]
  ...
  [2 2 2 ... 2 2 2]
  [2 1 1 ... 2 2 2]
  [2 2 2 ... 2 2 2]]]


In [23]:
print(data[-64:,:,:].shape)
print(data[-64:,:,:])

(64, 256, 256)
[[[2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  ...
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]]

 [[2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  ...
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]]

 [[2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  ...
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]
  [2 2 2 ... 8 8 8]]

 ...

 [[7 7 7 ... 2 2 2]
  [7 7 7 ... 2 2 2]
  [7 7 7 ... 2 2 2]
  ...
  [2 2 2 ... 1 1 3]
  [2 2 2 ... 2 1 1]
  [1 2 2 ... 3 1 1]]

 [[8 8 8 ... 7 7 7]
  [8 8 8 ... 7 7 7]
  [8 8 8 ... 7 7 7]
  ...
  [2 2 2 ... 2 2 2]
  [1 2 2 ... 2 2 2]
  [2 1 1 ... 2 2 2]]

 [[7 7 7 ... 7 7 7]
  [7 7 7 ... 7 7 7]
  [7 7 7 ... 7 7 7]
  ...
  [2 2 2 ... 2 2 2]
  [2 1 1 ... 2 2 2]
  [2 2 2 ... 2 2 2]]]
